name: TownyMenus
main: io.github.townyadvanced.townymenus.TownyMenus
version: ${version}
api-version: '1.20'
author: Warriorrr
website: 'https://townyadvanced.github.io'
folia-supported: true
depend: [Towny]

commands:
  townymenu:
    aliases:
      - tmenu
      - townygui
      - tgui
      - tm
    permission: townymenus.command.townymenu

permissions:
  townymenus.command.*:
    default: op
    children:
      townymenus.command.townymenu: true

  townymenus.command.townymenu:
    default: true
